In [1]:
import first_analysis
import enzyme_descriptors
import compound_descriptors
from DreamMLModels import *

In [2]:
# IMPORT DATA TO PANDAS OBEJECT:
print('\n IMPORT DATA TO PANDAS OBEJECT \n')
# data = pd.read_csv('data/DtcDrugTargetInteractions.csv', sep=',')


 IMPORT DATA TO PANDAS OBEJECT 



In [3]:
# a small one first to see if everithyng runs:
data = pd.read_csv('data/dreamInteractions_reduzido.csv', sep=',', index_col=0)

In [4]:
# ANALYZE THE DATA AND DELETE SOME ROWS WITHOUT INTEREST:
print('\n ANALYZE THE DATA AND DELETE SOME ROWS WITHOUT INTEREST \n')
first_analysis.look_at_data(data)
# Delete the rows withouth interest and make kd tranformations and conversions (lead with units too)
data = first_analysis.first_clean_and_transformations(data)


 ANALYZE THE DATA AND DELETE SOME ROWS WITHOUT INTEREST 

Data head:

           compound_id           standard_inchi_key compound_name synonym  \
3893402  CHEMBL1449346  RJIDGRHOHFDKKB-UHFFFAOYSA-N           NaN     NaN   
2744924  CHEMBL1456303  MNIPKPBXCNYLLX-UHFFFAOYSA-N           NaN     NaN   
2089192  CHEMBL1096032  JTTGRNWIRRFPKZ-UHFFFAOYSA-N           NaN     NaN   
4126374  CHEMBL1721911  SJACXJCFCJVRHS-UHFFFAOYSA-N           NaN     NaN   
3323555  CHEMBL1337862  OZBLYGXPDUZZSH-UHFFFAOYSA-N           NaN     NaN   

        target_id                      target_pref_name gene_names  \
3893402    O89049  THIOREDOXIN REDUCTASE 1, CYTOPLASMIC        NaN   
2744924    P00811                   BETA-LACTAMASE AMPC        NaN   
2089192    P11387                   DNA TOPOISOMERASE I       TOP1   
4126374    P43220      GLUCAGON-LIKE PEPTIDE 1 RECEPTOR      GLP1R   
3323555    P27467                        PROTEIN WNT-3A        NaN   

        wildtype_or_mutant mutation_info   pu

In [5]:
#COMPLETE COMPOUND ID WITH COMPOUND NAME
print('\n TRYING TO COMPLETE DATA \n')
data = first_analysis.complete_cols(data, 'compound_id', 'compound_name')
#see if there were any changes
print('Null values for column: \n')
print(data.isnull().sum())
print('\n')


#COMPLETE COUMPOUND ID WITH STANDARD_INCHI_KEY
data = first_analysis.complete_cols(data, 'compound_id', 'standard_inchi_key')
#see if there were any changes
print('Null values for column: \n')
print(data.isnull().sum())
print('\n')


#COMPLETE STANDARD_INCHI_KEY WITH COMPOUND ID
data = first_analysis.complete_cols(data, 'standard_inchi_key', 'compound_id')
#see if there were any changes
print('Null values for column: \n')
print(data.isnull().sum())
print('\n')


 TRYING TO COMPLETE DATA 

Null values for column: 

compound_id                           0
standard_inchi_key                    0
compound_name                        14
synonym                              58
target_id                             2
target_pref_name                      0
gene_names                            6
wildtype_or_mutant                   38
mutation_info                        57
pubmed_id                             0
standard_type                         0
standard_relation                     0
standard_value                        0
standard_units                        0
ep_action_mode                       38
assay_format                         33
assaytype                            38
assay_subtype                        38
inhibitor_type                       58
detection_tech                       38
assay_cell_line                      54
compound_concentration_value         38
compound_concentration_value_unit    38
substrate_type            

In [6]:
# GET COMPOUND DESCRIPTORS
print('\n GET COMPOUND DESCRIPTORS \n')
data = compound_descriptors.get_compound_descriptors(data, col_compound_id='compound_id', col_smiles='smiles', need_to_generate_similes=True)


 GET COMPOUND DESCRIPTORS 

Morgan
MACCS
MolLogP


In [7]:
# GET ENZYME SEQUENCES
print('\n GET ENZYME SEQUENCES \n')
data = enzyme_descriptors.add_sequence_col(data, 'target_id')


 GET ENZYME SEQUENCES 



/Users/martagomes/Documents/Bioinformatica/3Semestre/Sistemas_Inteligentes/Trabalho/dream_project/enzyme_descriptors.py:46: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data['sequence'] = data.apply(get_sequence, axis=1)


In [8]:
# GET ENZYME FEATURES FROM SEQUENCES
print('\n GET ENZYME FEATURES FROM SEQUENCES \n')
data = enzyme_descriptors.add_ProFet_features(data)


 GET ENZYME FEATURES FROM SEQUENCES 



In [9]:
#TRAINING MODELS
print('\n TRAINING MODELS \n')

#CREATE INSTANCES FOR THE MODEL CLASS
dream = DreamMLModels(data,(10,5)) # 10 lines to the test set (5 to evaluate the final model)
dream_feat_sel = DreamMLModels(data,(10,5), feature_selection=True)


 TRAINING MODELS 



/Users/martagomes/Documents/Bioinformatica/3Semestre/Sistemas_Inteligentes/Trabalho/dream_project/DreamMLModels.py:261: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data.dropna(axis=1, how='all', inplace=True)
/Users/martagomes/Documents/Bioinformatica/3Semestre/Sistemas_Inteligentes/Trabalho/dream_project/DreamMLModels.py:262: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  data.dropna(axis=0, inplace=True)
/Users/martagomes/anaconda3/lib/python3.6/site-packages/sklearn/utils/__init__.py:93: FutureWarning: Conversion of the second argument of issubdtype from `int` to `np.signedinteger` is deprecated. In future, it will be treated as `np.int64 == np.dty

In [10]:
#CREATE AND TEST MODELS
#create and evaluate all the models
print('\n *************************** ML Models ************************************\n')
modelos = dream.create_test_eval('ALL')


 *************************** ML Models ************************************


----------------------LR----------------------------

explained_variance_score:  0.29290711573167816
mean_absolute_error:  1.0820162357527328
mean_squared_error:  1.716862376455099
mean_squared_log_error:  0.029750178229747837
median_absolute_error:  0.7651965762787256
r2_score:  0.2925070778727107

-------------------------------------------------------------


----------------------NNT----------------------------

explained_variance_score:  -30915.61544311996
mean_absolute_error:  961.930888490585
mean_squared_error:  1000335.9174523521
mean_squared_log_error:  24.5351389040845
median_absolute_error:  808.9892272791728
r2_score:  -412222.24576098996

-------------------------------------------------------------


----------------------SVM----------------------------

explained_variance_score:  0.1255258604364139
mean_absolute_error:  0.886260565118536
mean_squared_error:  2.328110839888921
mean_squared_log

In [11]:
print("\n With feature selection: \n")
dream_feat_sel.create_test_eval('ALL')


 With feature selection: 


----------------------LR----------------------------

explained_variance_score:  0.5423251224815759
mean_absolute_error:  0.43371246759211635
mean_squared_error:  0.34726376752582955
mean_squared_log_error:  0.007235049750769241
median_absolute_error:  0.1944819879557409
r2_score:  0.39878711383163323

-------------------------------------------------------------


----------------------NNT----------------------------

explained_variance_score:  -291655.8590559051
mean_absolute_error:  1167.7644137011498
mean_squared_error:  1532136.2822335358
mean_squared_log_error:  26.77992502415318
median_absolute_error:  1126.765510570944
r2_score:  -2652565.0388004077

-------------------------------------------------------------


----------------------SVM----------------------------

explained_variance_score:  0.06249496029141455
mean_absolute_error:  0.6610574650932269
mean_squared_error:  0.5647113547530875
mean_squared_log_error:  0.012231237768197813
median_abso

[('LR',
  LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False),
  array([7.65544643, 6.04868862, 4.80551801, 4.99754422, 4.83250172])),
 ('NNT',
  MLPRegressor(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
         beta_2=0.999, early_stopping=False, epsilon=1e-08,
         hidden_layer_sizes=(100,), learning_rate='constant',
         learning_rate_init=0.001, max_iter=200, momentum=0.9,
         nesterovs_momentum=True, power_t=0.5, random_state=None,
         shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
         verbose=False, warm_start=False),
  array([ 768.14412085, 1131.76551057, 1539.44061739, 1731.67115133,
          694.70067713])),
 ('SVM',
  SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False),
  array([5.62818205, 5.62818205, 5.62818205, 5.14891447, 5.62818205])),
 ('RF', RandomForestRegressor(bootstrap=True, criterion

In [12]:
#Selecting the top features with random forests (only ProFet features)
print(dream.RF_feature_selection(100,True))

['SecondaryStr_3:  Mirror K-mer : ACACA', 'NormVDWV_3:  Mirror K-mer : AEEFA', 'SolventA_3:  Mirror K-mer : HAAHH', 'AA: Q Frequency', 'hp2: ACCCC', 'PI', 'Disorder_3:  Mirror K-mer : CCCCD', 'hp aaScale - Window size:17 Trimmed Average', 'SolventA_3:  Mirror K-mer : DDHHH', 'SecondaryStr_3:  Mirror K-mer : CADDC', 'Disorder_3:  Mirror K-mer : CADCC', 'Disorder_3:  Mirror K-mer : ADCCD', 'ofer14:  Mirror K-mer : AQ', 'Disorder_3:  Mirror K-mer : ACCCA', 'SecondaryStr_3:  Mirror K-mer : AAACC', 'ASAInTripeptide aaScale - Window size:17 Average-Trimmed MIN', 'ofer14:  Mirror K-mer : DG', 'Normalized VDWV Composition:3', 'Mutability aaScale - Window size:17 MAXIMUM ', 'SubSequence(segment-1)  aaScale:4Atch_2 Average', 'NormVDWV_3:  Mirror K-mer : AEFEE', 'ja aaScale - Window size:7 MAXIMUM ', 'Secondary Str Distribution1100', 'N Entropy', 'Charge Distribution2100', 'hp2: AAACA', 'GRAVY', 'Charge Distribution3100', 'SecondaryStr_3:  Mirror K-mer : ADACC', 'gg_9 aaScale - Window size:17 Ave